### PR TITLE
Alignment of json schemas fpr product with version 4

### PR DESCRIPTION
**Pull request by bartoszm**
Currently it is hard to say what type of schema our product definitions represent

### CODE REVIEW

**Comment by bartoszm** [comment]
Thanks for spotting that - change to title was not intentional

**Comment by bigludo7** [comment]
Hello
I saw you removed the @type & @schemaLocation attribute. Rationales for them was to provided a mechanism to extend product description for a given SP.

**Comment by bartoszm** [comment]
@bigludo7 I have removed them on purpose:
1. there is a mismatch in naming them between two product definitions @type  vs. @_type 
1. in my opinion these meta-attributes should and will be already present at the place where product definitions will be already injected (whether it is item/product or item/product/characteristics)

**Comment by bartoszm** [comment]
As discussed on IIS call - I perform the merge

**Pull request merged**
